-- https://github.com/fredsonchaves07/ToolsChallenge/issues/39
CREATE TABLE IF NOT EXISTS "TRANSACAO" (
	"ID"                  VARCHAR(36) NOT NULL,
    "TIPO_TRANSACAO"      VARCHAR(50) NOT NULL,
    "NUMERO_CARTAO"       VARCHAR(16) NOT NULL,
    "VALOR"               NUMERIC(15, 2) NOT NULL,
    "DATA_HORA"           TIMESTAMP NOT NULL,
    "ESTABELECIMENTO"     VARCHAR(255) NOT NULL,
    "CODIGO_NSU"          VARCHAR(11) NOT NULL,
    "CODIGO_AUTORIZACAO"  VARCHAR(9)  NOT NULL,
    "FORMA_DE_PAGAMENTO"  VARCHAR(255) NOT NULL,
    "PARCELAS"            INTEGER NOT NULL,
    "STATUS"              VARCHAR(30) NOT NULL,
    "CREATED_AT"          TIMESTAMP NOT NULL,
    "UPDATED_AT"          TIMESTAMP NOT NULL,
	PRIMARY KEY ("ID")
);